server:
  port: ${server.port}
  forward-headers-strategy: framework

spring:
  profiles:
    active: prod

  datasource:
    url: ${spring.datasource.url}
    username: ${spring.datasource.username}
    password: ${spring.datasource.password}
    driver-class-name: ${spring.datasource.driver-class-name}

  jpa:
    database: mysql
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    open-in-view: false


  flyway:
    enabled: false
    baseline-version: 1
    baseline-on-migrate: true
    locations: classpath:db/migration
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    schemas: public

logging:
  level:
    org.hibernate.sql: debug
    org.hibernate.type: trace

cloud:
  aws:
    credentials:
      access-key: ${cloud.aws.credentials.access-key}
      secret-key: ${cloud.aws.credentials.secret-key}
    s3:
      bucket: ${cloud.aws.s3.bucket}
    region:
      static: ${cloud.aws.region.static}
    stack:
      auto: false

cloudfront-domain-name: ${cloudfront-domain-name}

jwt:
  header: Authorization
  #dogfootbirdfootprintdogfootbirdfootprintdogfootbirdfootprintdogfootbirdfootprintdogfootbirdfootprint
  secret: ZG9nZm9vdGJpcmRmb290cHJpbnRkb2dmb290YmlyZGZvb3RwcmludGRvZ2Zvb3RiaXJkZm9vdHByaW50ZG9nZm9vdGJpcmRmb290cHJpbnRkb2dmb290YmlyZGZvb3RwcmludA==
  token-validity-in-seconds: 86400

management:
  endpoints:
    web:
      exposure:
        include: "prometheus"
      base-path:  "/api/actuator"

kakao:
  client_id: {kakao.cliend_id}
  redirect_uri: {kakao.redirect_uri}
  password: {kakao.password}